# version untuk docker
version: '3.8'

services:
  # Mendefinisikan menggunakan MySQL
  mysql:
    # Menggunakan image MySQL versi terbaru dari Docker Hub
    image: mysql:latest
    
    # Memberikan nama untuk container
    container_name: mysql_db
    
    # Mengatur port forwarding
    # Format: 'PORT_HOST:PORT_CONTAINER'
    # 3306 adalah port default MySQL
    ports:
      - '3306:3306'
    
    # Mengatur variabel lingkungan yang diperlukan untuk MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root    # Password untuk user root
      MYSQL_USER: user            # Membuat user baru
      MYSQL_PASSWORD: password    # Password untuk user baru
      MYSQL_DATABASE: test   # Membuat database baru
    
    # Mengatur volume untuk menyimpan data MySQL
    # Data akan tetap ada meskipun container dihapus
    volumes:
      - mysql_data:/var/lib/mysql

# Mendefinisikan volume yang akan digunakan
# Volume ini akan membuat data persisten
volumes:
  mysql_data:
    # Volume akan dibuat secara otomatis dengan nama default
    # Data akan disimpan di /var/lib/docker/volumes/